packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - astro@7.0.5
  - prettier@3.9.4
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/vite@4.3.2'
  - tailwindcss@4.3.2
  - '@astrojs/compiler-binding-darwin-arm64@0.3.0'
  - '@astrojs/compiler-binding-darwin-x64@0.3.0'
  - '@astrojs/compiler-binding-linux-arm64-gnu@0.3.0'
  - '@astrojs/compiler-binding-linux-arm64-musl@0.3.0'
  - '@astrojs/compiler-binding-linux-x64-gnu@0.3.0'
  - '@astrojs/compiler-binding-linux-x64-musl@0.3.0'
  - '@astrojs/compiler-binding-wasm32-wasi@0.3.0'
  - '@astrojs/compiler-binding-win32-arm64-msvc@0.3.0'
  - '@astrojs/compiler-binding-win32-x64-msvc@0.3.0'
  - '@astrojs/compiler-binding@0.3.0'
  - '@astrojs/compiler-rs@0.3.0'
  - '@types/node@26.1.0'

overrides:
  picomatch: '>=2.3.2'
  lodash: '>=4.18.0'
  fast-uri: '4.0.0'
  smol-toml: '1.7.0'
  yaml: '2.9.0'
  js-yaml: '5.1.0'
  '@astrojs/check': '0.9.9'

patchedDependencies:
  '@astrojs/internal-helpers@0.10.0': patches/@astrojs__internal-helpers@0.10.0.patch
  astro@7.0.5: patches/astro@7.0.5.patch
