name: Spell Check

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '**/*.md'
      - 'package.json'
      - '.cspell.json'
      - '.github/workflows/spellcheck.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '**/*.md'
      - 'package.json'
      - '.cspell.json'
      - '.github/workflows/spellcheck.yml'

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@26602fcdd72301b7f0dcc55023344f193389b9bf # v6
        with:
          files: |
            **/*.{ts,tsx,js,jsx,md,json}
          config: .cspell.json
          strict: false
