name: Spell Check

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '**/*.md'
      - 'package.json'
      - '.cspell.json'
      - '.github/workflows/spellcheck.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '**/*.md'
      - 'package.json'
      - '.cspell.json'
      - '.github/workflows/spellcheck.yml'

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          files: |
            **/*.{ts,tsx,js,jsx,md,json}
          config: .cspell.json
          strict: false
